### ISSUE TITLE
Error Aurelia-CLI & Tsc 

### ISSUE THREAD

**Issue by kielnevec** [wallaceturner/crypto-poker#3]
~/crypto-poker/poker.ui# au run -w
ERROR [CLI] The current directory is likely an Aurelia-CLI project, but no local installation of Aurelia-CLI could be found. (Do you need to restore node modules using npm install?)

===========================

../poker.ui/src/shared/decimal.ts:1:38 - error TS2307: Cannot find module 'decimal.js' or its corresponding type declarations.

1 import { Decimal as DecimalJS } from 'decimal.js';
                                       ~~~~~~~~~~~~

../poker.ui/src/shared/protobuf-config.ts:5:29 - error TS2307: Cannot find module 'protobufjs' or its corresponding type declarations.

5 import * as protobufjs from 'protobufjs';
                              ~~~~~~~~~~~~

Please kindly what is the issue with my server when installed it shows errors like above.

Thank you in advanced

**Comment by wallaceturner** [comment]
before running `au run -w` you will have to run `npm install`
Can you please try that? if that fixes it i will update the README
