### ISSUE TITLE
The game is not connected 

### ISSUE THREAD

**Issue by kielnevec** [wallaceturner/crypto-poker#4]
Thank you for updated documentation mate.
Also I have another issue.

for the client I can open it through browser localhost:9000 but its not connected to server.

![Capture22222](https://user-images.githubusercontent.com/7795612/96238330-8f7ad600-0fc8-11eb-8463-62b73947acc4.JPG)
![Capture2s](https://user-images.githubusercontent.com/7795612/96238677-f13b4000-0fc8-11eb-81c7-ace7acbb80e5.JPG)
![browser](https://user-images.githubusercontent.com/7795612/96238726-fdbf9880-0fc8-11eb-8633-342edf940da6.JPG)

Please kindly help my issue.
Thank you in advance

**Comment by wallaceturner** [comment]
open the console and see what errors there are please

**Comment by kielnevec** [comment]
would you please guide me ? what command to see the log

**Comment by wallaceturner** [comment]
Press F12  .

**Comment by kielnevec** [comment]
I think the server still on localhost but I access it using IP that shows error ..
how to fix it?

![Capturexxxx](https://user-images.githubusercontent.com/7795612/96253025-12a62700-0fdd-11eb-99da-988c3dab1dcb.JPG)

**Comment by wallaceturner** [comment]
it looks like you are trying to host this somewhere public? this tracker is for issues with the codebase per se, not basic programming how to - would advise a programming course first before tackling this project - it is not suited or aimed at beginners.
